#!/usr/bin/env python
# encoding: utf-8


def build_daemon(bld):
    smewtd = bld.create_obj('qt4', 'program')    
    smewtd.find_sources_in_dirs('smewtd')
    smewtd.uselib   = 'QTCORE QTGUI'
    smewtd.includes = '. smewtd'
    smewtd.target   = 'smewtdaemon'


def build(bld):
    build_daemon(bld)
