######################################################################
# Automatically generated by qmake (2.01a) Thu Apr 24 00:46:17 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
LIBS += -lsoprano -lsopranoclient

# Input
HEADERS += rdfviewer.h
SOURCES += main.cpp rdfviewer.cpp
