######################################################################
# Automatically generated by qmake (2.01a) Thu Apr 24 21:58:02 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
LIBS += -lsoprano -lsopranoclient

# Input
HEADERS += querywidget.h rdfviewer.h
SOURCES += main.cpp querywidget.cpp rdfviewer.cpp
