######################################################################
# Automatically generated by qmake (2.01a) Wed May 14 00:13:51 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
LIBS +=  -lcurl
QT += dbus

# Input
HEADERS += dljob.h smewtd.h
SOURCES += dljob.cpp main.cpp smewtd.cpp
