######################################################################
# Automatically generated by qmake (2.01a) Sun Mar 2 20:35:15 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += dljob.h dlwidget.h
SOURCES += dljob.cpp dlwidget.cpp main.cpp
LIBS += -lcurl
